AWSTemplateFormatVersion: '2010-09-09'

Description: >
  Creates CloudWatch monitoring for the highly available
  AWS web application.

Parameters:

  AutoScalingGroupName:
    Type: String
    Description: Name of the EC2 Auto Scaling Group

Resources:

  HighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Monitor high average CPU utilization
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 70
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref AutoScalingGroupName
      TreatMissingData: notBreaching

  LowCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Monitor low average CPU utilization
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 30
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref AutoScalingGroupName
      TreatMissingData: notBreaching

Outputs:

  HighCPUAlarmName:
    Description: CloudWatch alarm for high CPU utilization
    Value: !Ref HighCPUAlarm

  LowCPUAlarmName:
    Description: CloudWatch alarm for low CPU utilization
    Value: !Ref LowCPUAlarm